config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: "welcome#index"

  get "welcome/index"

  concern :attachable do
    resources :attachments
  end
  resources :attachments
  resources :users, concerns: :attachable
  resources :notes, concerns: :attachable
  resources :posts
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  has_many :extensions, dependent: :destroy

  has_one_attached :asset, dependent: :destroy
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController # rubocop:disable Metrics/ClassLength
  include Behaveable::ResourceFinder
  include Behaveable::RouteExtractor

  before_action :set_attachment, only: %i[show edit update destroy]

  # GET /attachments or /attachments.json
  def index
    @attachments = attachable.all

    respond_to do |format|
      format.html { render :index, status: :ok, location: extract(behaveable: @behaveable) }
      format.json { render json: @attachments, status: :ok, location: extract(behaveable: @behaveable) }
    end
  end

  # GET /attachments/1 or /attachments/1.json
  def show
    respond_to do |format|
      format.html { render :show, status: :ok, location: polymorphic_url([@behaveable, @attachment]) }
      format.json { render json: @attachment, status: :ok, location: polymorphic_url([@behaveable, @attachment]) }
    end
  end

  # GET /attachments/new
  def new
    @attachment = attachable.new
    respond_to do |format|
      format.html { render :new, status: :ok, location: polymorphic_url([@behaveable, @attachment]) }
      format.json { render json: @attachment, status: :ok, location: polymorphic_url([@behaveable, @attachment]) }
    end
  end

  # GET /attachments/1/edit
  def edit
    respond_to do |format|
      format.html { render :edit, status: :ok, location: extract(behaveable: @behaveable, resource: @attachment) }
      format.json do
        render json: @attachment, status: :ok, location: extract(behaveable: @behaveable, resource: @attachment)
      end
    end
  end

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength

  # POST /attachments or /attachments.json
  def create
    @attachment = attachable.new(attachment_params)

    respond_to do |format|
      @attachment.transaction do
        if @attachment.save
          attachable << @attachment if @behaveable

          @attachment.asset.attach(params[:attachment][:asset]) if params[:attachment][:asset]
          @attachment.asset.analyze if @attachment.asset.attached?

          format.html do
            redirect_to polymorphic_url([@behaveable, @attachment]), notice: "Attachment was successfully created."
          end
          format.json do
            render json: @attachment, status: :created, location: polymorphic_url([@behaveable, @attachment])
          end
        else
          format.html do
            render :new, status: :unprocessable_entity, location: polymorphic_url([@behaveable, @attachment])
          end
          format.json do
            render json: @attachment.errors, status: :unprocessable_entity,
                   location: polymorphic_url([@behaveable, @attachment])
          end
        end
      end
    end
  end

  # PATCH/PUT /attachments/1 or /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html do
          redirect_to polymorphic_url([@behaveable, @attachment]), notice: "Attachment was successfully updated."
        end
        format.json { render :edit, status: :ok, location: polymorphic_url([@behaveable, @attachment]) }
      else
        format.html do
          render :edit, status: :unprocessable_entity,
                        location: polymorphic_url([@behaveable, @attachment])
        end
        format.json do
          render json: @attachment.errors, status: :unprocessable_entity,
                 location: polymorphic_url([@behaveable, @attachment])
        end
      end
    end
  end

  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  # DELETE /attachments/1 or /attachments/1.json
  def destroy # rubocop:disable Metrics/MethodLength
    @attachment.destroy
    respond_to do |format|
      format.html do
        if @behaveable
          redirect_to @behaveable, notice: "Attachment was successfully destroyed."
        else
          redirect_to attachments_path, notice: "Attachment was successfully destroyed."
        end
      end
      format.json { head :no_content, location: extract(behaveable: @behaveable) }
    end
  end

  private

  # Get Attachment context object.
  #
  # ==== Returns
  # * <tt>ActiveRecord</tt> - Attachmentable's attachments or Attachment.
  def attachable
    @behaveable ||= behaveable
    @behaveable ? @behaveable.attachments : Attachment
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_attachment
    @attachment = attachable.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attachment_params
    params.require(:attachment).permit(
      :name,
      :asset
    )
  end
end

app/helpers/attachments_helper.rb
# frozen_string_literal: true

module AttachmentsHelper
  class RouteHelperError < StandardError; end

  def nested_helper_url(resource_name:, action: nil, behaveable: nil, resource: nil)
    location_url = location_url(resource_name: resource_name, action: action, behaveable: behaveable,
                                resource: resource)
    return regular(location_url: location_url, resource: resource) unless behaveable

    nested(location_url: location_url, behaveable: behaveable, resource: resource)
  end

  private

  def regular(location_url:, resource: nil)
    return send(location_url) unless resource

    send(location_url, resource)
  end

  def nested(location_url:, behaveable:, resource: nil)
    return send(location_url, behaveable) unless resource

    # action = resource_persisted?(resource) ? :update : :create
    # send(location_url, behaveable, resource, action: action)
    send(location_url, behaveable, resource)
  end

  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/MethodLength

  def location_url(resource_name:, action: nil, behaveable: nil, resource: nil)
    inflected_name = resource_name_inflection(resource_name: resource_name, resource: resource)
    behaveable_name = behaveable_name_from(behaveable) # Always singular

    url = behaveable ? "#{behaveable_name}_#{inflected_name}_url" : "#{inflected_name}_url"

    case action&.to_sym
    when :edit
      raise RouteHelperError, "Edit Route Need a Resource" unless resource

      "edit_#{url}"
    when :new
      raise RouteHelperError, "New Route Need a Resource" unless resource
      raise RouteHelperError, "Persisted Resource For New Route" if resource_persisted?(resource)

      "new_#{url}"
    else
      url
    end
  end

  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/MethodLength

  def resource_name_inflection(resource_name:, resource:)
    inflection = resource ? "singular" : "plural"
    resource_name.send("#{inflection}ize")
  end

  def behaveable_name_from(behaveable)
    return unless behaveable

    behaveable.class.name.underscore
  end

  def resource_persisted?(resource)
    return resource.persisted? if resource.respond_to?(:persisted?)

    !resource.id.nil?
  end
end

app/views/attachments/_form.html.erb
<% method = attachment.persisted? ? :patch : :post %>
<%= form_with(scope: :attachment, url: polymorphic_url([@behaveable, attachment]), method: method, local: true) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.file_field :asset, direct_upload: true %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', nested_helper_url(resource_name: "attachments", action: :show, behaveable: @behaveable, resource: @attachment) %> |
<%= link_to 'Back', nested_helper_url(resource_name: "attachments", action: :index, behaveable: @behaveable, resource: @attachment) %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td>
          <% if attachment.asset.attached? %>
            <%= image_tag url_for(attachment.asset.variant(resize: "50x50").processed) %>
          <% else %>
            No Attachment
          <% end %>
        </td>
        <td><%= attachment.name %></td>
        <td><%= link_to 'Show', nested_helper_url(resource_name: "attachments", action: :show, behaveable: @behaveable, resource: attachment) %></td>
        <td><%= link_to 'Edit', nested_helper_url(resource_name: "attachments", action: :edit, behaveable: @behaveable, resource: attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= (@behaveable || @attachment).name %>
</p>

<% if @attachment.asset.attached? %>
  <% if @attachment.asset.representable? %>
    <%= image_tag(url_for(@attachment.asset.representation(resize: "200x200").processed), id: "preview")%>
  <% else %>
    <%= image_tag url_for(@attachment.asset), class: "variant-1" %>
  <% end %>
<% else %>
  No Attachment
<% end %>

<br/>

<%= link_to 'Edit', nested_helper_url(resource_name: "attachments", action: :edit, behaveable: @behaveable, resource: @attachment) %> |
<%= link_to 'Back', nested_helper_url(resource_name: "attachments", behaveable: @behaveable) %> |

<% if @behaveable %>
  <%= link_to "Show #{@behaveable.class.name}", @behaveable %>
<% end %>